version: '3.8'
services:
  vue:
    build: .
    command: /bin/sh -c "cd vue-dynamic-component-test; npm install; npm run dev"
    ports:
      - 5173:5173
    volumes:
      - .:/app
    stdin_open: true
    tty: true